const API_URL='https://marvel-watchlist.onrender.com';
const SUPABASE_URL='https://ulfkgqttyyhqnieltkdn.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_qPynWf204MA04jy6sor7wg_cnvmHl0t';
let sb=null,user=null,titles=[],watched=new Set(),schedule={},typeFilter='all',watchFilter='all',activeId=null,authMode='login';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function initSB(){try{if(window.supabase?.createClient)sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY)}catch(e){console.error(e)}}
function show(id){const x=$(id);if(x)x.hidden=false}
function hide(id){const x=$(id);if(x)x.hidden=true}
function updateAuth(){const yes=!!user;$('loginBtn').hidden=yes;$('signupBtn').hidden=yes;$('logoutBtn').hidden=!yes;$('resetBtn').hidden=!yes;$('userEmail').hidden=!yes;$('userEmail').textContent=yes?user.email:''}
function openAuth(mode){authMode=mode;$('authModalTitle').textContent=mode==='login'?'Welcome back':'Join the timeline';$('authModalSubtitle').textContent=mode==='login'?'Log in to access your personal Marvel watchlist.':'Create an account and save your Marvel progress.';$('authSubmitBtn').textContent=mode==='login'?'Log In':'Create Account';$('authSwitchBtn').textContent=mode==='login'?'Need an account? Sign up':'Already have an account? Log in';$('authMessage').textContent='';show('authBackdrop');$('authEmail').focus()}
function closeAuth(){hide('authBackdrop')}
async function auth(){if(!sb){$('authMessage').textContent='Supabase failed to load. Refresh and try again.';return}const email=$('authEmail').value.trim(),password=$('authPassword').value;if(!email||!password){$('authMessage').textContent='Enter your email and password.';return}$('authSubmitBtn').disabled=true;try{const r=authMode==='login'?await sb.auth.signInWithPassword({email,password}):await sb.auth.signUp({email,password,options:{emailRedirectTo:location.origin}});if(r.error)throw r.error;if(authMode==='signup'&&!r.data.session){$('authMessage').textContent='Check your email to confirm your account, then log in.';return}user=r.data.user;await loadState();updateAuth();closeAuth();render()}catch(e){$('authMessage').textContent=e.message}finally{$('authSubmitBtn').disabled=false}}
async function loadState(){if(!sb||!user)return;const {data,error}=await sb.from('watchlist_state').select('title_id,watched,schedule_date,schedule_time');if(error){console.error(error);return}watched=new Set(data.filter(x=>x.watched).map(x=>x.title_id));schedule={};data.filter(x=>x.schedule_date).forEach(x=>schedule[x.title_id]={date:x.schedule_date,time:x.schedule_time||''})}
async function save(id){const {error}=await sb.from('watchlist_state').upsert({user_id:user.id,title_id:id,watched:watched.has(id),schedule_date:schedule[id]?.date||null,schedule_time:schedule[id]?.time||null},{onConflict:'user_id,title_id'});if(error)throw error}
function filtered(){const q=$('searchInput').value.toLowerCase(),phase=$('phaseFilter').value;return titles.filter(t=>(!q||JSON.stringify(t).toLowerCase().includes(q))&&(typeFilter==='all'||t.type===typeFilter)&&(watchFilter==='all'||(watchFilter==='watched')===watched.has(t.id))&&(phase==='all'||t.phase===phase||t.saga===phase))}
function render(){const list=filtered();$('timeline').innerHTML=list.map(t=>'<article class="title-card '+(watched.has(t.id)?'is-watched':'')+'"><div class="card-poster poster-'+(t.theme||1)+'"><span class="card-order">#'+esc(t.order)+'</span><span class="card-typebadge">'+esc(t.type||'')+'</span><span class="card-poster-glyph">'+esc(t.name)+'</span></div><div class="card-body"><h3 class="card-title">'+esc(t.name)+'</h3><div class="card-meta">'+esc(t.year)+' · '+esc(t.phase||'')+'</div><p class="card-notes">'+esc(t.notes||'')+'</p><div class="card-actions"><button class="watch-toggle-btn" data-watch="'+esc(t.id)+'">'+(watched.has(t.id)?'✓ Watched':'Mark Watched')+'</button><button class="schedule-btn" data-schedule="'+esc(t.id)+'">Schedule</button></div></div></article>').join('');$('emptyState').hidden=list.length>0;const total=titles.length,done=watched.size;$('statTotal').textContent=total;$('statCompleted').textContent=done;$('statRemaining').textContent=Math.max(0,total-done);$('progressText').textContent=done+' / '+total+' titles completed';$('progressPct').textContent=(total?Math.round(done/total*100):0)+'%';$('progressFill').style.width=(total?done/total*100:0)+'%'}
async function toggle(id){if(!user){openAuth('login');return}watched.has(id)?watched.delete(id):watched.add(id);render();try{await save(id)}catch(e){alert(e.message);await loadState();render()}}
function openSchedule(id){if(!user){openAuth('login');return}activeId=id;const t=titles.find(x=>x.id===id),s=schedule[id]||{};$('scheduleModalTitle').textContent='Schedule '+(t?.name||'watch');$('scheduleDate').value=s.date||'';$('scheduleTime').value=s.time||'';show('scheduleBackdrop')}
async function saveSchedule(){if(!activeId)return;if(!$('scheduleDate').value){alert('Choose a date.');return}schedule[activeId]={date:$('scheduleDate').value,time:$('scheduleTime').value};hide('scheduleBackdrop');render();try{await save(activeId)}catch(e){alert(e.message)}}
async function removeSchedule(){if(!activeId)return;delete schedule[activeId];hide('scheduleBackdrop');render();try{await save(activeId)}catch(e){alert(e.message)}}
async function boot(){initSB();updateAuth();document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.id==='loginBtn')openAuth('login');else if(b.id==='signupBtn')openAuth('signup');else if(b.id==='authClose')closeAuth();else if(b.id==='authSwitchBtn')openAuth(authMode==='login'?'signup':'login');else if(b.id==='authSubmitBtn')auth();else if(b.id==='logoutBtn'){if(sb)await sb.auth.signOut();user=null;watched=new Set();schedule={};updateAuth();render()}else if(b.dataset.watch)toggle(b.dataset.watch);else if(b.dataset.schedule)openSchedule(b.dataset.schedule);else if(b.id==='scheduleSave')saveSchedule();else if(b.id==='scheduleRemove'){await removeSchedule()}else if(b.id==='scheduleClose')hide('scheduleBackdrop');else if(b.dataset.filterType){typeFilter=b.dataset.filterType;document.querySelectorAll('[data-filter-type]').forEach(x=>x.classList.toggle('active',x===b));render()}else if(b.dataset.filterWatch){watchFilter=b.dataset.filterWatch;document.querySelectorAll('[data-filter-watch]').forEach(x=>x.classList.toggle('active',x===b));render()}});$('searchInput').addEventListener('input',render);$('phaseFilter').addEventListener('change',render);try{if(sb){const {data:{session}}=await sb.auth.getSession();user=session?.user||null;if(user)await loadState();updateAuth()}const r=await fetch(API_URL+'/api/titles');titles=await r.json();titles.sort((a,b)=>(a.order||0)-(b.order||0));const phases=[...new Set(titles.map(x=>x.phase).filter(Boolean))];$('phaseFilter').innerHTML='<option value="all">All Phases</option>'+phases.map(p=>'<option>'+esc(p)+'</option>').join('');render()}catch(e){console.error(e);$('timeline').innerHTML='<p class="empty-state">Could not load titles.</p>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();